image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf cmake
    - git submodule init
    - git submodule update
  script:
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build . -j16
    - cd ..

  artifacts:
    paths:
      - build/cpu_6502_emulator


test:
  stage: test
  script:
    - ./build/cpu_6502_emulator
