FROM ubuntu:22.04

WORKDIR /ws

RUN apt update && \
	apt install -y \
	git \
	cmake \
	g++ \
	clang \
	clang-format \
	clang-tidy \
	qt6-base-dev \
	build-essential \
	libgl1-mesa-dev

ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o cpu6502
RUN useradd -m -u $UID -g $GID -o -s /bin/bash cpu6502

USER cpu6502

WORKDIR /ws

