name: Arch

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: FetchSubmodules
      run: |
        git submodule init
        git submodule update

    - name: Build the Docker image
      run: make build DOCKERFILE=Dockerfile.arch

    - name: GCC tests
      run: make test_gcc DOCKERFILE=Dockerfile.arch

    - name: Clang tests
      run: make test_clang DOCKERFILE=Dockerfile.arch

    # Clang-tidy stucks on arch
#    - name: Static analysis
#      run: make clang_tidy DOCKERFILE=Dockerfile.arch
