name: clang-tidy

on:
  push:
    branches:  
      - '**' 
  pull_request:
    branches:
       - '**' 

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y install g++ gcc qt6-base-dev build-essential libgl1-mesa-dev clang-tidy
    
    - name: FetchSubmodules
      run: |
        git submodule init
        git submodule update
        
    - name: ClangTidy
      run: |
        mkdir -p build_debug
        cd build_debug
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_CLANG_TIDY=True
        cmake --build . -j

