name: clang

on:
  push:
    branches:  
      - '**' 
  pull_request:
    branches:
       - '**' 

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y install clang qt6-base-dev build-essential libgl1-mesa-dev valgrind
    
    - name: FetchSubmodules
      run: |
        git submodule init
        git submodule update
        
    - name: BuildRelease
      run: |
        mkdir -p build_release
        cd build_release
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . -j

    - name: TestRelease
      run: |
        cd build_release
        valgrind ./cpu_6502_test

    - name: BuildDebug
      run: |
        mkdir -p build_debug
        cd build_debug
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build . -j

    - name: TestDebug
      run: |
        cd build_debug
        valgrind ./cpu_6502_test

