name: CMake

on:
  push:
    branches:  
      - '**' 
  pull_request:
    branches:
       - '**' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt -y install g++-11
    
    - name: FetchSubmodules
      run: |
        git submodule init
        git submodule update
        
    - name: Build
      run: |
        export CXX=g++-11
        export CC=gcc-11
        mkdir -p build
        cd build
        cmake ../
        cmake -build . -j

#    - name: Test
#     run: TEST_HERE
      
