name: CMake

on:
  push:
    branches:  
      - '**' 
  pull_request:
    branches:
       - '**' 

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt -y install g++ gcc qt6-tools-dev-tools
    
    - name: FetchSubmodules
      run: |
        git submodule init
        git submodule update
        
    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ../
        cmake --build . -j

    - name: Test
      run: |
        cd build
        ./cpu_6502_test
      
